import Header from "../components/Header";
import styles from './about.module.scss'
import Head from "next/head";
import * as THREE from 'three'
import { Canvas, useFrame } from '@react-three/fiber';
import { ScrollControls, Scroll, GradientTexture, MeshDistortMaterial, useCursor} from '@react-three/drei';
import { useRef, useState } from 'react'


function about() {
    const dumping = 2

    const Ball = (props) => {
        const materialRef = useRef()
        const meshRef = useRef()

        const [hovered, hover] = useState(false)
        useCursor(hovered)
      
            useFrame(() => {
                return(
                materialRef.current.distort = THREE.MathUtils.lerp(materialRef.current.distort, hovered ? 0.4 : 0.2, hovered ? 0.05 : 0.01),
                meshRef.current.rotation.y += 0.005,
                )
              })

        return(
            <mesh ref={meshRef} position={[-3,0,0]} onPointerOver={() => hover(true)} onPointerOut={() => hover(false)} >
            <sphereGeometry args={[1.7, 20, 40, 100]} />
            <MeshDistortMaterial ref={materialRef}speed={5}>
             <GradientTexture stops={[0, 0.8, 1]} colors={['#e63946', '#f1faee', '#a8dadc']} size={100} />
             </MeshDistortMaterial>
            </mesh>
        )
    }
   

    return (
        <div>
            <Head>
            <title>About - YM</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

            </Head>
            <div className={styles.container}>
            <Header />
            <Canvas>
                <ScrollControls pages={2} dumping={2}>
                    <Scroll >
                        <ambientLight intensity={0.5} />
                        <spotLight position={[5,5,5]} />
                        <Ball />
                 
                    </Scroll>
               

                    <Scroll html>
                        <div className={styles.content}>
                            <h1>About<br/>Myself</h1>
                            <span className={styles.line}></span>
                            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Distinctio earum inventore tempora quam fugiat alias. Nobis, eveniet deserunt. Nisi eos modi alias debitis vel provident nostrum ullam incidunt est quidem?</p>
                        </div>
                    </Scroll>

                </ScrollControls>
            </Canvas>
            </div>
        </div>
    );
}

export default about;